[package]
name = "jsonRpc"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.8"
bitcoincore-rpc = "0.19.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"